### ISSUE TITLE
SSL connection 

### ISSUE THREAD

**Issue by guigautier** [DanielBok/private-conda-repo#4]
Hi, 
Thanks a lot for sharing this project.
I want to run the pcr server with ssl using docker-compose.
I did a specific test docker-compose.yml file.

_version: "3.7"

 

services:
  web:
    image: danielbok/pcr-web-ssl:3.0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/private-conda-repo/certs:/etc/nginx/certs
    depends_on: 
      - server

 

  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pcrdb
    volumes:
      - pcrdb:/var/lib/postgresql/data
  
  server:
    image: danielbok/pcr-server:3.0
    ports:
      - "5050:5050"
      - "5060:5060"
    environment: 
      PCR_INDEXER.TYPE: shell
    volumes: 
      - /var/condapkg:/var/condapkg
      # if overriding default config file
      # - C:/temp/my-config.yaml:/var/private-conda-repo/config.yaml
    depends_on: 
      - postgres

 

volumes:
  pcrdb:_

When I try to connect from web interface, I can't log in we my registered channel and password.
"Could not retrieve package data. Reason: Server is likely to be down"
Have you ever encountered this issue ? any hints will be helpful, thanks.

**Comment by DanielBok** [comment]
Hello, 

There are teething bugs in the react web.. Haven't had time to solve it but would do so when I can since it's just a simple rewiring of the api layer.

In the meanwhile, use the cli tool. You can find the documentation for it at the [cli section](https://github.com/DanielBok/private-conda-repo/tree/master/cli)

And you can download it from the [releases section](https://github.com/DanielBok/private-conda-repo/releases/tag/3.0)

**Comment by guigautier** [comment]
Thanks for your quick answer.
 I will continue to use it without ssl for now.

**Comment by DanielBok** [comment]
@guigautier I've fixed up the frontend. Tested that it works locally. I'll close this issue now. Feel free to raise it again if you encounter bugs
